version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - projector-network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  projector-network:
volumes:
  postgres:
  pgadmin: